In [57]:
# Don't need requests unless we get the data live
# import requests
import pandas as pd
import numpy as np
import matplotlib as plt
import plotly.express as px
import json
import os 
import time 
import requests

# For plotly to work you also need to install the statsmodels package as well

# Get live data from FPL site. Not necessary to do every time. 
# TODO: Write if statement to get live data if old else file .
# TODO: Add penalties to data

url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
r = requests.get(url)
json = r.json()


# We still have to use json.load here to load the data before handing it off to pandas. 
# Even though pandas can directly parse some json data, it can't seem to easily handle this. 
# It would probably work with json_normalize but I can't get it to work. 

#with open('/home/adam/jupyter/fpl/bootstrap-static.json') as json_data:
#    data = json.load(json_data)

elements_df = pd.DataFrame(data['elements'])
elements_types_df = pd.DataFrame(data['element_types'])
teams_df = pd.DataFrame(data['teams'])

# Get all data for one player to see what fields we want to grab
elements_example = elements_df.iloc[3]
elements_example

elements_df.head()

#attacking_returns_df = elements_df[['first_name','second_name','element_type','now_cost','minutes','total_points','goals_scored','assists']].copy()

# # # Change from positional values to their actual names
# attacking_returns_df['position'] = attacking_returns_df.element_type.map(elements_types_df.set_index('id').singular_name)


# # Set minimum threshold of 500 minutes 
# attacking_returns_df = attacking_returns_df.loc[attacking_returns_df.minutes > 500]
# attacking_returns_df['cost'] = (attacking_returns_df.now_cost.astype(float) / 10)
# attacking_returns_df['name'] = attacking_returns_df['first_name'] + ' ' + attacking_returns_df['second_name']
# small_df = attacking_returns_df.drop(columns=['first_name', 'second_name', 'now_cost', 'element_type'])

# outfield_df = small_df.loc[small_df.position != 'Goalkeeper']


# # Starting out with a smaller table to test
# test_df = outfield_df

# # Add column for name without accents
# sanitized_names = test_df.name.str.normalize('NFKD')\
#                               .str.encode('ascii', errors='ignore')\
#                               .str.decode('utf-8')

# test_df['sanitized_name'] = sanitized_names

# test_df.to_json("/home/adam/jupyter/fpl/fpl_data.json")

# # Starting out putting xG_90 in its own table

# xG_90_column_names = ["name","np_goals_90","npgx_90","assists_90","xA_90"]

# xG_90 = pd.DataFrame(columns = xG_90_column_names)

# count = 0

# for player_name in test_df['sanitized_name']:
#     # Get data in a format fbref expects
#     new_name = player_name.replace(' ', '+').lower()
#     # TODO: Add in try / except / catch for this because I don't think I'll get 100% success rate. 
#     url = 'https://fbref.com/en/search/search.fcgi?search='+new_name
#     print(player_name)
#     try: 
#         fbref_player_stats = pd.read_html("{}".format(url), index_col=0)[0]
#         np_goals_90 = fbref_player_stats.loc['Non-Penalty Goals','Per 90']
#         npxg_90 = fbref_player_stats.loc['npxG','Per 90']
#         assists_90 = fbref_player_stats.loc['Assists','Per 90']
#         xA_90 = fbref_player_stats.loc['xA','Per 90']
#         # Add this data as a row to the new xG dataframe
#         xG_90.loc[count] = [player_name, np_goals_90, npxg_90, assists_90, xA_90]
#     # Get data at a reasonable rate form fbref. Don't abuse the site.
#     except Exception as e:
#         print(e)
#         xG_90.loc[count] = [player_name, "NA", "NA", "NA", "NA"]
#     count +=1
#     time.sleep(10)

# xG_90    
# xG_90.to_csv("/home/adam/jupyter/fpl/outfield_xG_data.csv", index=False)

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,NaN,None,80201,0,0,0,0,0,1,3.5,...,320,4,194,12,NaN,,NaN,,NaN,
1,NaN,None,115918,0,0,0,0,0,1,2.0,...,332,12,350,31,NaN,,NaN,,NaN,
2,NaN,None,47431,0,0,0,0,0,3,3.2,...,145,84,123,70,1.0,,2.0,,NaN,
3,NaN,None,54694,0,0,0,0,0,4,4.2,...,32,16,50,18,NaN,,NaN,,1.0,
4,NaN,None,58822,0,0,0,0,0,2,2.7,...,261,84,289,97,NaN,,5.0,,NaN,